services:
  - type: web
    name: coffee-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        vvalue: 3.12.0  # Или 3.11.0
      - key: TELEGRAM_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true