services:
  - type: web
    name: coffee-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true